Repository hkdobrev/run-if-changed, pull requests merged in 2019-11, with the labels that each got.

#9 Run diff recursively to allow more granularity
  src/gitChangedFilesSinceLastHead.js
Labels: bug

#13 Remove commander dependency
  package.json
  run-if-changed.js
  src/cliInit.js
  yarn.lock
Labels: cleanup

#14 Add GitHub action for lint/test
  .github/workflows/js_test.yml
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#17 Publish to npm and GitHub packages via Actions
  .github/workflows/publish.yml
Labels: enhancement

#16 Deduplicate commands for each run
  run-if-changed.js
  src/findBinary.js
  src/resolveMatchingPatterns.js
  src/runForMatchingPatterns.js
Labels: enhancement
